# Generated by Django 5.0.6 on 2024-06-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(max_length=10)),
                ('foto', models.ImageField(upload_to='media')),
                ('descripcion_lugar', models.TextField(max_length=500)),
            ],
        ),
    ]
